INSERT INTO AGENT (ID, GLOBAL_CONFIG, NAME, TYPE) VALUES (1, '2323423423', 'AGENT 1', 'FIRST');

INSERT INTO MODULE (ID, NAME, TYPE, AGENT_ID) VALUES (1, 'MOD 1', 'INPUT', 1);
INSERT INTO MODULE (ID, NAME, TYPE, AGENT_ID) VALUES (2, 'MOD 2', 'PROCESSOR', 1);
INSERT INTO MODULE (ID, NAME, TYPE, AGENT_ID) VALUES (3, 'MOD 3', 'EXTENSION', 1);
INSERT INTO MODULE (ID, NAME, TYPE, AGENT_ID) VALUES (4, 'MOD 4', 'OUTPUT', 1);

INSERT INTO ROUTE (ID, NAME, PRIORITY, AGENT_ID) VALUES (1, 'ROUTE 1', 1, 1);

INSERT INTO MODULE_ROUTE (ID, MODULE_ID, ROUTE_ID) VALUES (1, 1, 1);
INSERT INTO MODULE_ROUTE (ID, MODULE_ID, ROUTE_ID) VALUES (2, 2, 1);
INSERT INTO MODULE_ROUTE (ID, MODULE_ID, ROUTE_ID) VALUES (3, 4, 1);

INSERT INTO ROUTE (ID, NAME, PRIORITY, AGENT_ID) VALUES (2, 'ROUTE 2', 2, 1);

INSERT INTO MODULE_ROUTE (ID, MODULE_ID, ROUTE_ID) VALUES (5, 1, 2);
INSERT INTO MODULE_ROUTE (ID, MODULE_ID, ROUTE_ID) VALUES (6, 2, 2);